#!/bin/bash
#
# This is a wrapper around ansible / ansible-playbook.
#
# Usage ("ansible-playbook" mode):
#
#   ./ansible/mastodonsible [--prod]
#
# If you are unfamiliar with Ansible, read up on it at
# - https://www.ansible.com/overview/how-ansible-works
# - https://github.com/jdauphant/awesome-ansible

cd "$(dirname "$0")"; cd "$(/bin/pwd)"

git_current_branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
case "$git_current_branch" in
    "") : ;;
    *) playbook_flags="$playbook_flags -e git_current_branch=$git_current_branch" ;;
esac

warn () {
    if [ -n "$1" ]; then
        echo "$@" >&2
    else
        cat >&2
    fi
}

fatal () {
    warn "$@"
    exit 1
}


ansible_suitcase_dir () {
    echo $PWD/ansible-deps-cache
}

ensure_suitcase () {
    if ! test -f ansible-deps-cache/.versions 2>/dev/null; then
      curl https://raw.githubusercontent.com/epfl-si/ansible.suitcase/master/install.sh | \
            SUITCASE_ANSIBLE_VERSION=10.3.0 \
            SUITCASE_DIR=$PWD/ansible-deps-cache \
            SUITCASE_ANSIBLE_REQUIREMENTS=requirements.yml \
            SUITCASE_NO_EYAML=1 \
            bash -x
    fi

    . "$(ansible_suitcase_dir)"/lib.sh
    ensure_ansible_runtime
}

inventory_mode="test"
inventories () {
    case "$inventory_mode" in
        *test*) echo "-i inventory/test.yml -e inventory_mode=test" ;;
    esac
    case "$inventory_mode" in
        *prod*) echo "-i inventory/prod.yml -e inventory_mode=prod" ;;
    esac
}

###########################################################################

mode=ansible-playbook

while [ "$#" -gt 0 ]; do
    case "$1" in
        --prod)
            inventory_mode="prod"
            shift ;;
        -m) mode=ansible
            ansible_args+=("-m")
            shift ;;
        *)
            ansible_args+=("$1")
            shift ;;
    esac
done

# https://github.com/ansible/ansible/issues/32499, https://bugs.python.org/issue35219
case "$(uname -s)" in
    Darwin) export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ;;
esac

set -e

ensure_suitcase
case "$mode" in
    ansible-playbook)
        ansible-playbook $playbook_flags  $(inventories) "${ansible_args[@]}" \
                         $ansible_flags \
                         playbook.yml
        ;;
    ansible)
        ansible $(inventories) $ansible_flags "${ansible_args[@]}"
        ;;
esac
