- name: "Setup the VM"
  hosts: all
  gather_facts: yes
  roles:
    - role: roles/setup

- name: "External Docker network"
  hosts: all
  gather_facts: no
  tags:
    - traefik
    - mastodon
    - mastodon.setup
    - mastodon.setup.docker-network
  vars_files:
    - roles/mastodon/vars/mastodon-vars.yml
  tasks:
    - community.docker.docker_network:
        name: "{{ mastodon_docker_external_network_name }}"

- name: "Setup Traefik"
  hosts: all
  gather_facts: no
  tags:
    - traefik
  roles:
    - epfl_si.traefik.traefik
  vars_files:
    - versions.yml   # For traefik_docker_image
    - roles/mastodon/vars/mastodon-vars.yml   # For mastodon_web_container_name + mastodon_docker_external_network_name
  vars:
    traefik_root_location: /srv/traefik
    traefik_docker_networks:
      - name: "{{ mastodon_docker_external_network_name }}"
      - name: "{{ mastodon_docker_internal_network_name }}" # Metrics
    traefik_use_acme_prod_ca: true
  tasks:
    - epfl_si.traefik.dynamic_config:
        name: mastodon
        content: |
          http:
            services:
              mastodon:
                loadBalancer:
                  servers:
                  - url: http://{{ mastodon_web_container_name }}:3000
            routers:
              mastodon:
                rule: Host(`{{ inventory_hostname }}`)
                service: mastodon
                tls:
                  certResolver: letsencrypt

- name: "Setup Mastodon"
  hosts: all
  gather_facts: no
  roles:
    - role: roles/mastodon

- name: "Setup monitoring"
  hosts: all
  gather_facts: no
  roles:
    - role: roles/monitoring
