groups:
  - name: Disks monitoring
    rules:
    - alert: "{{ inventory_hostname }} main disk is nearly full"
      expr: {% raw -%}
      'floor(node_filesystem_free_bytes{mountpoint="/"} / 1048576) < 5 * 1024'
{% endraw %}
      for: 15m
      labels:
        owner: mastodon-admin
      annotations:
        summary: "{{ inventory_hostname }} main disk is nearly full"
        description: {% raw -%}
        "The {{ $labels.fstype }} partition {{ $labels.device }} ({{ $labels.mountpoint }}) has only {{ $value }} megabytes remaining."
{% endraw %}

    - alert: "{{ inventory_hostname }} backups disk is nearly full"
      expr: {% raw -%}
      'floor(node_filesystem_free_bytes{mountpoint="/srv/backups"} / 1048576) < 5 * 1024'
{% endraw %}
      for: 15m
      labels:
        owner: mastodon-admin
      annotations:
        summary: "{{ inventory_hostname }} backups disk is nearly full"
        description: {% raw -%}
        "The {{ $labels.fstype }} partition {{ $labels.device }} ({{ $labels.mountpoint }}) has only {{ $value }} megabytes remaining."
{% endraw %}

    - alert: "{{ inventory_hostname }} user's uploads disk is nearly full"
      expr: {% raw -%}
      'floor(node_filesystem_free_bytes{mountpoint="/srv/mastodon/web"} / 1048576) < 5 * 1024'
{% endraw %}
      for: 15m
      labels:
        owner: mastodon-admin
      annotations:
        summary: "{{ inventory_hostname }} user's uploads disk is nearly full"
        description: {% raw -%}
        "The {{ $labels.fstype }} partition {{ $labels.device }} ({{ $labels.mountpoint }}) has only {{ $value }} megabytes remaining."
{% endraw %}

    - alert: "{{ inventory_hostname }} disk with cache is nearly full"
      expr: {% raw -%}
      'floor(node_filesystem_free_bytes{mountpoint="/srv/mastodon/web/public/system/cache"} / 1048576) < 5 * 1024'
{% endraw %}
      for: 15m
      labels:
        owner: mastodon-admin
      annotations:
        summary: "{{ inventory_hostname }} disk with cache is nearly full"
        description: {% raw -%}
        "The {{ $labels.fstype }} partition {{ $labels.device }} ({{ $labels.mountpoint }}) has only {{ $value }} megabytes remaining."
{% endraw %}
