mastodon_docker_internal_network_name: mastodon-internal

mastodon_postgresql_dir: /srv/mastodon/postgres14
mastodon_postgresql_container_name: mastodon-postgresql

mastodon_postgresql_database: mastodon
mastodon_postgresql_user: mastodon
mastodon_postgresql_port: 5432

