- name: Prometheus directory
  ansible.builtin.file:
    state: directory
    recurse: yes
    path: "{{ prometheus_dir }}/data"
    owner: 65534
    group: 65534
    mode: '0755'

- name: Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: "{{ prometheus_dir }}/prometheus.yml"
  register: _prom_config_change

- name: Prometheus container
  community.docker.docker_container:
    name: "{{ prometheus_container_name }}"
    image: "{{ prometheus_image }}"
    networks:
      - name: "{{ mastodon_docker_internal_network_name }}"
    volumes:
      - "{{ prometheus_dir }}/data:/prometheus"
      - "{{ prometheus_dir }}/prometheus.yml:/etc/prometheus/prometheus.yml"
    exposed_ports:
      - 9090
    restart_policy: 'unless-stopped'
    restart: "{{ _prom_config_change.changed }}"
