- name: Prometheus directory
  ansible.builtin.file:
    state: directory
    recurse: yes
    path: "{{ prometheus_dir }}/{{ item }}"
    owner: 65534
    group: 65534
    mode: '0755'
  with_items:
    - data
    - rules

- name: Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: "{{ prometheus_dir }}/prometheus.yml"
  register: _prom_config_change

- name: Copy prometheus rules
  template: 
    src: "{{ item }}"
    dest: "{{ prometheus_dir }}/rules/{{ item | basename }}"
  with_fileglob:
    - "templates/alerts/*.yml"
  register: _prom_rules

- name: Prometheus container
  community.docker.docker_container:
    name: "{{ prometheus_container_name }}"
    image: "{{ prometheus_image }}"
    networks:
      - name: "{{ mastodon_docker_internal_network_name }}"
    volumes:
      - "{{ prometheus_dir }}/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "{{ prometheus_dir }}/data:/prometheus"
      - "{{ prometheus_dir }}/rules:/rules"
    ports:
      - 9090:9090
    restart_policy: 'unless-stopped'
    restart: >-
      {{
        _prom_config_change.changed 
        or
        (_prom_rules | default({})) is changed
      }}
