- name: Create backups folder for Mastodon
  ansible.builtin.file:
    path: "{{ item }}/"
    state: directory
  loop:
    - "{{ mastodon_backups_dir }}/database"
    - "{{ mastodon_backups_dir }}/files"
  tags: 
    - mastodon
    - mastodon.setup
    - mastodon.backup
    - mastodon.backup.database
    - mastodon.backup.uploads

- name: Manage Mastodon database's backups
  block:
    - name: Cron to run pg_dump for mastodon database ({{ mastodon_backups_dir }}/database/)
      ansible.builtin.cron:
        user: root
        name: pg_dump mastodon db every 4 hours
        minute: 0
        hour: "4-20/4"
        job: "export COMPOSE_INTERACTIVE_NO_CLI=1; \
              docker exec {{ mastodon_postgresql_container_name }} \
              pg_dump -Fc -U postgres -d mastodon | gzip > \
              {{ mastodon_backups_dir }}/database/$(date +\\%F_\\%H\\%M\\%S)_mastodon_db.tar.gz"
    - name: Cron to run pg_dumpall ({{ mastodon_backups_dir }}/database/)
      ansible.builtin.cron:
        user: root
        name: pg_dumpall at 4:02 am
        minute: 2
        hour: 4
        job: "export COMPOSE_INTERACTIVE_NO_CLI=1; \
              docker exec {{ mastodon_postgresql_container_name }} \
              pg_dumpall -c -U postgres > \
              {{ mastodon_backups_dir }}/database/$(date +\\%A)_morning_pgdumpall.dump"
    - name: Backup rotation (database)
      ansible.builtin.cron:
        user: root
        name: rotate daily Mastodon database backups at 4:06 am
        minute: 6
        hour: 4
        job: "mv $(ls -t {{ mastodon_backups_dir }}/database/$(date -d 'yesterday' '+\\%Y-\\%m-\\%d')_*_mastodon_db.tar.gz | head -1) \
              $(date -d 'yesterday' +\\%A)_mastodon_db.tar.gz \
              && \
              rm -f {{ mastodon_backups_dir }}/database/$(date -d 'yesterday' '+\\%Y-\\%m-\\%d')_*_mastodon_db.tar.gz"
  tags:
    - mastodon.backup
    - mastodon.backup.database

- name: Manage Mastodon uploads's backups
  block:
    - name: Cron to backup Mastodon's uploads every 4 hours
      ansible.builtin.cron:
        user: root
        name: backup Mastodon's uploads every 4 hours
        minute: 4
        hour: "*/4"
        job: "tar -czf {{ mastodon_backups_dir }}/files/$(date +\\%F_\\%H\\%M\\%S)_mastodon_files.tar.gz --exclude='cache' /srv/mastodon/web/public/system/"
    - name: Backup rotation (uploads)
      ansible.builtin.cron:
        user: root
        name: rotate daily Mastodon uploads backups at 4:08 am
        minute: 8
        hour: 4
        job: "mv $(ls -t {{ mastodon_backups_dir }}/files/$(date -d 'yesterday' '+\\%Y-\\%m-\\%d')_*_mastodon_files.tar.gz | head -1) \
              $(date -d 'yesterday' +\\%A)_mastodon_files.tar.gz \
              && \
              rm -f {{ mastodon_backups_dir }}/files/$(date -d 'yesterday' '+\\%Y-\\%m-\\%d')_*_mastodon_files.tar.gz"
  tags:
    - mastodon.backup
    - mastodon.backup.uploads
