# This is permayellow and have to be improved (aka WIP)

- name: "Migrate and seed the database"
  docker_container:
    name: migrate-and-seed
    image: "{{ mastodon_web_image }}"
    detach: false
    command:
    - bundle
    - exec
    - rake
    - "{{ item }}"
    env: "{{ mastodon_env }}"
    network_mode: "{{ mastodon_docker_internal_network_name }}"
  with_items:
    - db:migrate
    - db:seed
