- tags: always
  include_vars: "{{ item }}"
  with_items:
  - versions.yml
  - mastodon-vars.yml

- name: Mastodon prerequisites
  include_tasks:
    file: setup.yml
    apply:
      tags:
        - mastodon
        - mastodon.setup
  tags:
    - mastodon
    - mastodon.setup
    - mastodon.setup.docker-network

- name: Mastodon database (Redis)
  include_tasks:
    file: redis.yml
    apply:
      tags:
        - mastodon
        - mastodon.redis
  tags:
    - mastodon
    - mastodon.redis
    - mastodon.redis.purge

- name: Mastodon database (PostgreSQL)
  include_tasks:
    file: postgresql.yml
    apply:
      tags:
        - mastodon
        - mastodon.pg
  tags:
    - mastodon
    - mastodon.pg
    - mastodon.pg.purge

- name: Mastodon configure
  include_tasks:
    file: configure.yml
    apply:
      tags:
        - mastodon
        - mastodon.configure
  tags:
    - mastodon
    - mastodon.configure

- name: Mastodon frontend (Web)
  include_tasks:
    file: web.yml
    apply:
      tags:
        - mastodon
        - mastodon.web
  tags:
    - mastodon
    - mastodon.web
    - mastodon.web.run
    - mastodon.streaming.run
    - mastodon.sidekiq.run
