- tags: always
  include_vars: "{{ item }}"
  with_items:
  - versions.yml
  - mastodon-vars.yml

- name: Mastodon prerequisites
  include_tasks:
    file: setup.yml
    apply:
      tags:
        - mastodon
        - mastodon.setup
  tags:
    - mastodon
    - mastodon.setup
    - mastodon.setup.docker-network

- name: Mastodon database (PostgreSQL)
  include_tasks:
    file: postgresql.yml
    apply:
      tags:
        - mastodon
        - mastodon.pg
  tags:
    - mastodon
    - mastodon.pg
    - mastodon.pg.purge

- name: Mastodon run
  include_tasks:
    file: run.yml
    apply:
      tags:
        - mastodon
        - mastodon.run
  tags:
    - mastodon
    - mastodon.run
