- name: Stop PostgreSQL container
  when: >-
    "mastodon.pg.purge" in ansible_run_tags
  tags:
  - mastodon.pg.purge
  community.docker.docker_container:
    name: "{{ mastodon_postgresql_container_name }}"
    state: absent

- name: Purge PostgreSQL state
  when: >-
    "mastodon.pg.purge" in ansible_run_tags
  tags:
  - mastodon.pg.purge
  ansible.builtin.file:
    state: absent
    path: "{{ mastodon_postgresql_dir }}/data"

- name: PostgreSQL directories
  ansible.builtin.file:
    state: directory
    recurse: yes
    path: "{{ item }}"
  with_items:
    - "{{ mastodon_postgresql_dir }}/data"
    - "{{ mastodon_postgresql_dir }}/initdb"

- name: Initialization script for PostgreSQL
  ansible.builtin.template:
    src: init-db-mastodon.sql.j2
    dest: "{{ mastodon_postgresql_dir }}/initdb/init-db-mastodon.sql"

- name: PostgreSQL container
  community.docker.docker_container:
    name: "{{ mastodon_postgresql_container_name }}"
    image: "{{ mastodon_postgresql_image }}"
    state: healthy
    shm_size: 256MB
    network_mode: "{{ mastodon_docker_internal_network_name }}"
    volumes:
      - "{{ mastodon_postgresql_dir }}/data:/var/lib/postgresql/data"
      - "{{ mastodon_postgresql_dir }}/initdb:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    env:
      POSTGRES_HOST_AUTH_METHOD: trust
