- name: Deploy Mastodon with docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{ mastodon_dir }}"
  register: output
  tags: 
    - mastodon
    - mastodon.run

- name: Show results
  ansible.builtin.debug:
    var: output
  tags: 
    - mastodon
    - mastodon.run
