- name: Create folder for Mastodon
  ansible.builtin.file:
    path: "{{ mastodon_dir }}/"
    state: directory
  tags: 
    - mastodon
    - mastodon.setup

- name: "Admins' Makefile for Mastodon"
  ansible.builtin.template:
    src: Makefile.j2
    dest: "{{ mastodon_dir }}/Makefile"
  tags: 
    - mastodon
    - mastodon.setup

- name: Internal Docker network
  community.docker.docker_network:
     name: "{{ mastodon_docker_internal_network_name }}"
  tags:
    - mastodon
    - mastodon.setup
    - mastodon.setup.docker-network

- name: .env for Mastodon
  ansible.builtin.template:
    src: mastodon.env.j2
    dest: "{{ mastodon_dir }}/.env"
  tags: 
    - mastodon
    - mastodon.setup
