# Give access to ISAS-FSD members
- name: Allow some of ISAS-FSD members SSH access
  become: true
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "https://github.com/{{ item }}.keys"
  with_items:
    - domq
    - dwesh163
    - lvenries
    - ponsfrilus
  tags:
    - setup
    - setup.ssh

# Install Docker
- name: Install required packages
  become: true
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
  tags:
    - setup
    - setup.docker

- name: Create directory for Docker's GPG key
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags:
    - setup
    - setup.docker

- name: Add Docker's official GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present
  tags:
    - setup
    - setup.docker

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64
      signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker
    state: present
  tags:
    - setup
    - setup.docker

- name: Install Docker and related packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  tags:
    - setup
    - setup.docker

- name: Add Docker group
  become: true
  ansible.builtin.group:
    name: docker
    state: present
  tags:
    - setup
    - setup.docker

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  tags:
    - setup
    - setup.docker

- name: Enable and start Docker services
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service
    - containerd.service
  tags:
    - setup
    - setup.docker

- name: Set the message of the day with service info
  become: true
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
  tags:
    - setup
    - setup.motd
