{
 "title": "Mastodon@EPFL",
 "tags": [ "Mastodon" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "<img src='https://raw.githubusercontent.com/epfl-si/mastodon.ops/8acd3a36898938dbf51442faa67d9816e5e6e5c8/media/Mastodon%40EPFL.svg' height='100%'>\n"
   }
  },
  {
   "title": "Users count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_mastodon_user_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Local statuses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_mastodon_local_status_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local boosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_mastodon_local_boost_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local favourites",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_mastodon_local_favourite_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Statuses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_mastodon_status_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Favourites",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_mastodon_favourite_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Boosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_mastodon_boost_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mastodon@EPFL's users",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 4 },
   "targets": [
    { "expr": "ruby_mastodon_user_count", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Disc usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 4 },
   "targets": [
    {
     "expr": "100.0 - 100 * ((node_filesystem_avail_bytes{mountpoint=\"/\"} / 1000 / 1000 ) / (node_filesystem_size_bytes{mountpoint=\"/\"}  / 1024 / 1024))",
     "legendFormat": "Disc usage of {{mountpoint}}"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_http_requests_total{controller=\"api/v1/statuses\", status=\"200\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ruby_http_requests_total{controller=\"api/v1/statuses\", status!=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}